-- SQL Script to create Enterprise licenses for Organization 1 and Organization 2
-- This script creates licenses with all features enabled

-- Insert license for Organization 1
INSERT INTO licenses (
    "licenseKey",
    "type",
    "plan",
    "status",
    "billingCycle",
    "validUntil",
    "lastValidated",
    "maxUsers",
    "maxBranches",
    "storageLimit",
    "apiCallLimit",
    "integrationLimit",
    "features",
    "price",
    "organisationRef",
    "hasPendingPayments",
    "createdAt",
    "updatedAt",
    "isDeleted"
) VALUES (
    UPPER(MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT)), -- Generate unique license key
    'enterprise',
    'enterprise',
    'active',
    'annual',
    NULL, -- No expiry (perpetual)
    CURRENT_TIMESTAMP,
    999999, -- Unlimited users
    999999, -- Unlimited branches
    1048576, -- 1TB storage in MB (1024 * 1024)
    10000000, -- 10M API calls
    999999, -- Unlimited integrations
    '{
        "approvals.access": true,
        "approvals.basic": true,
        "approvals.advanced": true,
        "approvals.premium": true,
        "approvals.enterprise": true,
        "assets.access": true,
        "assets.view": true,
        "assets.advanced": true,
        "assets.tracking": true,
        "assets.enterprise": true,
        "claims.access": true,
        "claims.view": true,
        "claims.management": true,
        "claims.premium": true,
        "claims.enterprise": true,
        "clients.access": true,
        "clients.basic": true,
        "clients.advanced": true,
        "clients.premium": true,
        "clients.enterprise": true,
        "communication.access": true,
        "communication.advanced": true,
        "communication.premium": true,
        "communication.enterprise": true,
        "competitor.analysis": true,
        "docs.access": true,
        "docs.premium": true,
        "docs.enterprise": true,
        "journal.access": true,
        "journal.view": true,
        "journal.advanced": true,
        "journal.premium": true,
        "journal.enterprise": true,
        "leads.access": true,
        "leads.basic": true,
        "leads.advanced": true,
        "leads.premium": true,
        "leads.enterprise": true,
        "leave.access": true,
        "licensing.access": true,
        "licensing.manage": true,
        "news.access": true,
        "news.view": true,
        "news.announcements": true,
        "news.enterprise": true,
        "notifications.access": true,
        "notifications.basic": true,
        "notifications.advanced": true,
        "notifications.enterprise": true,
        "organisation.access": true,
        "organisation.basic": true,
        "organisation.advanced": true,
        "organisation.enterprise": true,
        "products.access": true,
        "products.view": true,
        "products.advanced": true,
        "products.premium": true,
        "products.enterprise": true,
        "reports.access": true,
        "reports.basic": true,
        "reports.advanced": true,
        "reports.premium": true,
        "reports.enterprise": true,
        "resellers.access": true,
        "resellers.management": true,
        "resellers.enterprise": true,
        "rewards.access": true,
        "rewards.gamification": true,
        "rewards.enterprise": true,
        "shop.access": true,
        "shop.basic": true,
        "shop.advanced": true,
        "shop.premium": true,
        "shop.enterprise": true,
        "tasks.access": true,
        "tasks.basic": true,
        "tasks.advanced": true,
        "tasks.premium": true,
        "tasks.enterprise": true,
        "tracking.access": true,
        "tracking.mapping": true,
        "tracking.unlimited": true,
        "tracking.enterprise": true,
        "users.access": true,
        "users.basic": true,
        "users.advanced": true,
        "users.premium": true,
        "users.enterprise": true,
        "warnings.access": true,
        "payslips.access": true,
        "payslips.basic": true,
        "payslips.advanced": true,
        "payslips.premium": true,
        "payslips.enterprise": true,
        "quotations.basic": true,
        "quotations.advanced": true,
        "inventory.single_location": true,
        "inventory.multi_location": true,
        "mobile.basic": true,
        "mobile.offline": true,
        "support.email": true,
        "support.priority": true,
        "support.technical_priority": true,
        "support.dedicated_manager": true,
        "platform.hr": true,
        "platform.sales": true,
        "platform.crm": true,
        "platform.all": true,
        "geofencing.basic": true,
        "geofencing.unlimited": true,
        "route.optimization": true,
        "route.advanced_optimization": true,
        "branches.multi_management": true,
        "feedback.advanced": true,
        "api.access": true,
        "integrations.custom": true,
        "branding.white_label": true,
        "analytics.predictive": true
    }'::jsonb,
    999.00,
    1, -- Organisation 1
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    false
);

-- Insert license for Organization 2
INSERT INTO licenses (
    "licenseKey",
    "type",
    "plan",
    "status",
    "billingCycle",
    "validUntil",
    "lastValidated",
    "maxUsers",
    "maxBranches",
    "storageLimit",
    "apiCallLimit",
    "integrationLimit",
    "features",
    "price",
    "organisationRef",
    "hasPendingPayments",
    "createdAt",
    "updatedAt",
    "isDeleted"
) VALUES (
    UPPER(MD5(RANDOM()::TEXT || CLOCK_TIMESTAMP()::TEXT)), -- Generate unique license key
    'enterprise',
    'enterprise',
    'active',
    'annual',
    NULL, -- No expiry (perpetual)
    CURRENT_TIMESTAMP,
    999999, -- Unlimited users
    999999, -- Unlimited branches
    1048576, -- 1TB storage in MB (1024 * 1024)
    10000000, -- 10M API calls
    999999, -- Unlimited integrations
    '{
        "approvals.access": true,
        "approvals.basic": true,
        "approvals.advanced": true,
        "approvals.premium": true,
        "approvals.enterprise": true,
        "assets.access": true,
        "assets.view": true,
        "assets.advanced": true,
        "assets.tracking": true,
        "assets.enterprise": true,
        "claims.access": true,
        "claims.view": true,
        "claims.management": true,
        "claims.premium": true,
        "claims.enterprise": true,
        "clients.access": true,
        "clients.basic": true,
        "clients.advanced": true,
        "clients.premium": true,
        "clients.enterprise": true,
        "communication.access": true,
        "communication.advanced": true,
        "communication.premium": true,
        "communication.enterprise": true,
        "competitor.analysis": true,
        "docs.access": true,
        "docs.premium": true,
        "docs.enterprise": true,
        "journal.access": true,
        "journal.view": true,
        "journal.advanced": true,
        "journal.premium": true,
        "journal.enterprise": true,
        "leads.access": true,
        "leads.basic": true,
        "leads.advanced": true,
        "leads.premium": true,
        "leads.enterprise": true,
        "leave.access": true,
        "licensing.access": true,
        "licensing.manage": true,
        "news.access": true,
        "news.view": true,
        "news.announcements": true,
        "news.enterprise": true,
        "notifications.access": true,
        "notifications.basic": true,
        "notifications.advanced": true,
        "notifications.enterprise": true,
        "organisation.access": true,
        "organisation.basic": true,
        "organisation.advanced": true,
        "organisation.enterprise": true,
        "products.access": true,
        "products.view": true,
        "products.advanced": true,
        "products.premium": true,
        "products.enterprise": true,
        "reports.access": true,
        "reports.basic": true,
        "reports.advanced": true,
        "reports.premium": true,
        "reports.enterprise": true,
        "resellers.access": true,
        "resellers.management": true,
        "resellers.enterprise": true,
        "rewards.access": true,
        "rewards.gamification": true,
        "rewards.enterprise": true,
        "shop.access": true,
        "shop.basic": true,
        "shop.advanced": true,
        "shop.premium": true,
        "shop.enterprise": true,
        "tasks.access": true,
        "tasks.basic": true,
        "tasks.advanced": true,
        "tasks.premium": true,
        "tasks.enterprise": true,
        "tracking.access": true,
        "tracking.mapping": true,
        "tracking.unlimited": true,
        "tracking.enterprise": true,
        "users.access": true,
        "users.basic": true,
        "users.advanced": true,
        "users.premium": true,
        "users.enterprise": true,
        "warnings.access": true,
        "payslips.access": true,
        "payslips.basic": true,
        "payslips.advanced": true,
        "payslips.premium": true,
        "payslips.enterprise": true,
        "quotations.basic": true,
        "quotations.advanced": true,
        "inventory.single_location": true,
        "inventory.multi_location": true,
        "mobile.basic": true,
        "mobile.offline": true,
        "support.email": true,
        "support.priority": true,
        "support.technical_priority": true,
        "support.dedicated_manager": true,
        "platform.hr": true,
        "platform.sales": true,
        "platform.crm": true,
        "platform.all": true,
        "geofencing.basic": true,
        "geofencing.unlimited": true,
        "route.optimization": true,
        "route.advanced_optimization": true,
        "branches.multi_management": true,
        "feedback.advanced": true,
        "api.access": true,
        "integrations.custom": true,
        "branding.white_label": true,
        "analytics.predictive": true
    }'::jsonb,
    999.00,
    2, -- Organisation 2
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    false
);

-- Verify the licenses were created
SELECT 
    "uid",
    "licenseKey",
    "type",
    "plan",
    "status",
    "organisationRef",
    "maxUsers",
    "maxBranches",
    "storageLimit",
    "createdAt"
FROM licenses
WHERE "organisationRef" IN (1, 2)
ORDER BY "organisationRef";
