export enum AccessLevel {
	OWNER = 'owner',
	ADMIN = 'admin',
	MANAGER = 'manager',
	SUPERVISOR = 'supervisor',
	USER = 'user',
	DEVELOPER = 'developer',
	SUPPORT = 'support',
	ANALYST = 'analyst',
	ACCOUNTANT = 'accountant',
	AUDITOR = 'auditor',
	CONSULTANT = 'consultant',
	COORDINATOR = 'coordinator',
	SPECIALIST = 'specialist',
	TECHNICIAN = 'technician',
	TRAINER = 'trainer',
	RESEARCHER = 'researcher',
	OFFICER = 'officer',
	EXECUTIVE = 'executive',
	CASHIER = 'cashier',
	RECEPTIONIST = 'receptionist',
	SECRETARY = 'secretary',
	SECURITY = 'security',
	CLEANER = 'cleaner',
	MAINTENANCE = 'maintenance',
	EVENT_PLANNER = 'event planner',
	MARKETING = 'marketing',
	HR = 'hr',
	CLIENT = 'client',
	FINANCE = 'finance',
	ACCOUNTING = 'accounting',
	LEGAL = 'legal',
	OPERATIONS = 'operations',
	IT = 'it',
	DEVELOPMENT = 'development',
	DESIGN = 'design',
}

export enum Department {
	SUPPORT = 'support',
	ENGINEERING = 'engineering',
	SALES = 'sales',
	MARKETING = 'marketing',
	FINANCE = 'finance',
	HR = 'hr',
	LEGAL = 'legal',
	OPERATIONS = 'operations',
	IT = 'it',
	CUSTOMER_SERVICE = 'customer service',
	PRODUCTION = 'production',
	RESEARCH = 'research',
	DEVELOPMENT = 'development',
	DESIGN = 'design',
	CONTENT = 'content',
	ACCOUNTING = 'accounting',
	AUDITING = 'auditing',
	CONSULTING = 'consulting',
	COORDINATION = 'coordination',
	COORDINATOR = 'coordinator',
	TECHNICIAN = 'technician',
	TRAINER = 'trainer',
	RESEARCHER = 'researcher',
	OFFICER = 'officer',
	EXECUTIVE = 'executive',
}

export enum Theme {
	LIGHT = 'light',
	DARK = 'dark',
	SYSTEM = 'system',
}

export enum Language {
	ENGLISH = 'en',
	AFRIKAANS = 'af',
	ZULU = 'zu',
	XHOSA = 'xh',
	SOTHO = 'st',
	TSWANA = 'tn',
	TSONGA = 'ts',
	SWATI = 'ss',
	VENDA = 've',
	NDEBELE = 'nr',
	PEDI = 'nso',
}

export enum NotificationFrequency {
	REAL_TIME = 'real_time',
	HOURLY = 'hourly',
	DAILY = 'daily',
	WEEKLY = 'weekly',
	DISABLED = 'disabled',
}

export enum DateFormat {
	DD_MM_YYYY = 'DD/MM/YYYY',
	MM_DD_YYYY = 'MM/DD/YYYY',
	YYYY_MM_DD = 'yyyy-MM-dd',
	DD_MMM_YYYY = 'DD MMM YYYY',
}

export enum TimeFormat {
	TWELVE_HOUR = '12h',
	TWENTY_FOUR_HOUR = '24h',
}
